# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54fa0510e07f4e68d4a85f9ad611f1be1907bab3f29d65abf1bc43934bbce5ff46666778515f8ae5e2c1defeafd8e5047e671a5e53e198d0c6af1053b5306471

test:
  secret_key_base: 2692801124766b74fdb78f29589a9cf9d3b54187994d90769f506e289213a9b33bb91095ea73ee09902b5c9bf330a4e6b72bce5784247cdb03a981df65ae9764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
